### ISSUE TITLE
embed JSON-LD metadata in each layer page

### ISSUE THREAD

**Issue by jmckenna** [SAEON/mims-catalog#1]
- leveraged by Google Dataset Search, and [ODIS](https://oceaninfohub.org/), for discovering each record

related to https://github.com/iodepo/odis-arch/issues/250

**Comment by marksparkza** [comment]
Added commits (work in progress):
https://github.com/SAEON/odp-core/commit/a722584044a4d60fd251f8a9f49abc4361758aa7
https://github.com/SAEON/odp-server/commit/1c32402fc28ac068833f28bc4991e4c7227fa3fe

**Comment by marksparkza** [comment]
@jmckenna Thanks for opening this issue and facilitating integration of the MIMS catalogue with ODIS!

I've closed this issue as a usable (I believe) implementation is now live in our production MIMS catalogue. Please feel free to open new issues if any problems arise with harvesting from your side, or if any info seems to be incorrect or missing in the JSON-LD metadata or the sitemap. I will be reviewing these changes with our curation team in the near future, which may lead to further updates (e.g. including dataset creators). I'll open new issues for any such changes.
